name: Build Cross Platform

on:
  workflow_dispatch: # 手动触发
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: node18-linux-x64
            output: model-edge-exporter-linux
          - os: windows-latest
            target: node18-win-x64
            output: model-edge-exporter-win.exe

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install pkg
      run: npm install -g pkg

    - name: Build
      run: pkg --targets ${{ matrix.target }} --output dist/${{ matrix.output }} main.js

    - name: Copy WASM files
      shell: bash
      run: |
        mkdir -p dist
        cp zstd.wasm dist/ 2>/dev/null || echo "zstd.wasm not found"
        cp node_modules/sql.js/dist/sql-wasm.wasm dist/sql-wasm.wasm 2>/dev/null || echo "sql-wasm.wasm not found"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.output }}
        path: |
          dist/${{ matrix.output }}
          dist/*.wasm

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/${{ matrix.output }}
          dist/*.wasm
