name: Build Cross Platform

on:
    workflow_dispatch:
    push:
        branches: [main, master]

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: node18-linux-x64
                      output: model-edge-exporter-linux-x64
                      arch: x64
                    - os: ubuntu-latest
                      target: node18-linux-arm64
                      output: model-edge-exporter-linux-arm64
                      arch: arm64
                    - os: windows-latest
                      target: node18-win-x64
                      output: model-edge-exporter-win.exe
                      arch: x64

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  architecture: ${{ matrix.arch }}

            - name: Install dependencies
              run: npm ci

            - name: Install pkg
              run: npm install -g pkg

            - name: Build with pkg
              run: pkg . --targets ${{ matrix.target }} --output dist/${{ matrix.output }}

            - name: Copy WASM files to output directory
              shell: bash
              run: |
                  mkdir -p dist
                  cp zstd.wasm dist/ 2>/dev/null || echo "zstd.wasm not found"
                  cp node_modules/sql.js/dist/sql-wasm.wasm dist/sql-wasm.wasm 2>/dev/null || echo "sql-wasm.wasm not found"
                  ls -la dist/

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.output }}
                  path: |
                      dist/${{ matrix.output }}
                      dist/*.wasm

            - name: Create Release (on tag)
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/${{ matrix.output }}
                      dist/*.wasm
