name: Build Cross Platform

on:
    workflow_dispatch:
    push:
        branches: [main, master]

jobs:
    build-x64:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: node18-linux-x64
                      output: model-edge-exporter-linux-x64
                    - os: windows-latest
                      target: node18-win-x64
                      output: model-edge-exporter-win.exe

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Install pkg
              run: npm install -g pkg

            - name: Build with pkg
              run: pkg . --targets ${{ matrix.target }} --output dist/${{ matrix.output }}

            - name: Copy WASM files to output directory
              shell: bash
              run: |
                  mkdir -p dist
                  cp zstd.wasm dist/ 2>/dev/null || echo "zstd.wasm not found"
                  cp node_modules/sql.js/dist/sql-wasm.wasm dist/sql-wasm.wasm 2>/dev/null || echo "sql-wasm.wasm not found"

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.output }}
                  path: |
                      dist/${{ matrix.output }}
                      dist/*.wasm

    build-arm64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Build ARM64 in Docker
              run: |
                  docker run --rm --platform linux/arm64 \
                    -v ${{ github.workspace }}:/workspace \
                    -w /workspace \
                    node:18-alpine sh -c "
                      npm ci --ignore-scripts &&
                      npm install -g pkg &&
                      pkg . --targets node18-linux-arm64 --output dist/model-edge-exporter-linux-arm64 &&
                      mkdir -p dist &&
                      cp zstd.wasm dist/ 2>/dev/null || echo 'zstd.wasm not found' &&
                      cp node_modules/sql.js/dist/sql-wasm.wasm dist/sql-wasm.wasm 2>/dev/null || echo 'sql-wasm.wasm not found'
                    "

            - name: Upload ARM64 artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: model-edge-exporter-linux-arm64
                  path: |
                      dist/model-edge-exporter-linux-arm64
                      dist/*.wasm
